// enrich-missing.js — Manually enrich the 379 words WordNet doesn't cover
// Outputs _missing_enriched.json, then merge into words-enriched.json
const fs = require('fs');
const path = require('path');
const https = require('https');

const missing = fs.readFileSync(path.join(__dirname, '_missing_from_wordnet.txt'), 'utf8')
    .split('\n').map(w => w.trim()).filter(Boolean);

console.log(`Processing ${missing.length} missing words...\n`);

// ── Manual definitions for all categories ───────────────────────────

const manualEntries = {
    // ── Pronouns, articles, determiners, prepositions, conjunctions ──
    the:       { pos: ['article'], def: 'definite article used before nouns', syn: [] },
    a:         { pos: ['article'], def: 'indefinite article used before singular nouns', syn: [] },
    an:        { pos: ['article'], def: 'indefinite article used before vowel sounds', syn: [] },
    and:       { pos: ['conjunction'], def: 'used to connect words, phrases, or clauses', syn: ['plus', 'also', 'as well as'] },
    or:        { pos: ['conjunction'], def: 'used to indicate an alternative', syn: ['alternatively', 'otherwise'] },
    but:       { pos: ['conjunction'], def: 'used to introduce a contrasting statement', syn: ['however', 'yet', 'nevertheless'] },
    for:       { pos: ['preposition', 'conjunction'], def: 'indicating purpose; because', syn: ['because', 'since'] },
    nor:       { pos: ['conjunction'], def: 'used to introduce a further negative statement', syn: ['neither'] },
    if:        { pos: ['conjunction'], def: 'introducing a conditional clause', syn: ['provided', 'assuming', 'whether'] },
    of:        { pos: ['preposition'], def: 'expressing the relationship between a part and a whole', syn: [] },
    to:        { pos: ['preposition'], def: 'expressing direction or position', syn: ['toward', 'towards'] },
    into:      { pos: ['preposition'], def: 'expressing movement or direction to a point within', syn: ['inside', 'within'] },
    onto:      { pos: ['preposition'], def: 'moving to a position on the surface of', syn: ['upon', 'on'] },
    upon:      { pos: ['preposition'], def: 'on; used in formal or literary contexts', syn: ['on', 'onto', 'atop'] },
    unto:      { pos: ['preposition'], def: 'to (archaic or formal)', syn: ['to', 'toward'] },
    from:      { pos: ['preposition'], def: 'indicating the point of origin', syn: [] },
    with:      { pos: ['preposition'], def: 'accompanied by; having', syn: ['alongside', 'together'] },
    without:   { pos: ['preposition'], def: 'in the absence of', syn: ['lacking', 'minus'] },
    against:   { pos: ['preposition'], def: 'in opposition to', syn: ['opposing', 'versus', 'contra'] },
    among:     { pos: ['preposition'], def: 'in the middle of; surrounded by', syn: ['amid', 'amongst', 'between'] },
    amidst:    { pos: ['preposition'], def: 'in the middle of; surrounded by', syn: ['amid', 'among', 'amongst'] },
    beside:    { pos: ['preposition'], def: 'at the side of; next to', syn: ['alongside', 'next to', 'near'] },
    during:    { pos: ['preposition'], def: 'throughout the course of', syn: ['through', 'throughout', 'in'] },
    since:     { pos: ['preposition', 'conjunction'], def: 'from a past time until now; because', syn: ['because', 'as', 'from'] },
    until:     { pos: ['preposition', 'conjunction'], def: 'up to the point in time that', syn: ['till', 'up to', 'before'] },
    unless:    { pos: ['conjunction'], def: 'except on the condition that', syn: ['if not', 'except if'] },
    although:  { pos: ['conjunction'], def: 'in spite of the fact that', syn: ['though', 'even though'] },
    albeit:    { pos: ['conjunction'], def: 'although; even though', syn: ['although', 'though', 'even if'] },
    because:   { pos: ['conjunction'], def: 'for the reason that', syn: ['since', 'as', 'due to'] },
    than:      { pos: ['conjunction', 'preposition'], def: 'used in comparisons', syn: [] },
    that:      { pos: ['pronoun', 'conjunction', 'determiner'], def: 'referring to a specific thing; used to introduce a clause', syn: ['which', 'who'] },
    this:      { pos: ['pronoun', 'determiner'], def: 'referring to something nearby or just mentioned', syn: [] },
    these:     { pos: ['pronoun', 'determiner'], def: 'plural of this', syn: [] },
    those:     { pos: ['pronoun', 'determiner'], def: 'plural of that', syn: [] },
    which:     { pos: ['pronoun', 'determiner'], def: 'asking for information specifying one of a set', syn: ['what', 'that'] },
    whether:   { pos: ['conjunction'], def: 'expressing a doubt or choice between alternatives', syn: ['if'] },
    whereas:   { pos: ['conjunction'], def: 'in contrast or comparison with the fact that', syn: ['while', 'although', 'but'] },
    toward:    { pos: ['preposition'], def: 'in the direction of', syn: ['towards', 'to'] },
    towards:   { pos: ['preposition'], def: 'in the direction of', syn: ['toward', 'to'] },
    per:       { pos: ['preposition'], def: 'for each; by means of', syn: ['each', 'every'] },
    via:       { pos: ['preposition'], def: 'by way of; through', syn: ['through', 'by'] },
    versus:    { pos: ['preposition'], def: 'against; as opposed to', syn: ['against', 'vs', 'compared to'] },

    // ── Personal pronouns ───────────────────────────────────────────
    i:         { pos: ['pronoun'], def: 'first person singular pronoun', syn: ['me', 'myself'] },
    me:        { pos: ['pronoun'], def: 'objective case of I', syn: [] },
    my:        { pos: ['pronoun', 'determiner'], def: 'belonging to me', syn: ['mine'] },
    myself:    { pos: ['pronoun'], def: 'reflexive form of I/me', syn: [] },
    we:        { pos: ['pronoun'], def: 'first person plural pronoun', syn: ['us'] },
    our:       { pos: ['pronoun', 'determiner'], def: 'belonging to us', syn: ['ours'] },
    ourselves: { pos: ['pronoun'], def: 'reflexive form of we/us', syn: [] },
    you:       { pos: ['pronoun'], def: 'second person pronoun', syn: [] },
    your:      { pos: ['pronoun', 'determiner'], def: 'belonging to you', syn: ['yours'] },
    yourself:  { pos: ['pronoun'], def: 'reflexive form of you', syn: [] },
    he:        { pos: ['pronoun'], def: 'third person singular masculine pronoun', syn: ['him'] },
    him:       { pos: ['pronoun'], def: 'objective case of he', syn: [] },
    his:       { pos: ['pronoun', 'determiner'], def: 'belonging to him', syn: [] },
    himself:   { pos: ['pronoun'], def: 'reflexive form of he/him', syn: [] },
    she:       { pos: ['pronoun'], def: 'third person singular feminine pronoun', syn: ['her'] },
    her:       { pos: ['pronoun', 'determiner'], def: 'objective case of she; belonging to her', syn: ['hers'] },
    herself:   { pos: ['pronoun'], def: 'reflexive form of she/her', syn: [] },
    it:        { pos: ['pronoun'], def: 'third person singular neuter pronoun', syn: [] },
    its:       { pos: ['pronoun', 'determiner'], def: 'belonging to it', syn: [] },
    itself:    { pos: ['pronoun'], def: 'reflexive form of it', syn: [] },
    they:      { pos: ['pronoun'], def: 'third person plural pronoun', syn: ['them'] },
    them:      { pos: ['pronoun'], def: 'objective case of they', syn: [] },
    their:     { pos: ['pronoun', 'determiner'], def: 'belonging to them', syn: ['theirs'] },
    theirs:    { pos: ['pronoun'], def: 'possessive form: belonging to them', syn: [] },
    themselves:{ pos: ['pronoun'], def: 'reflexive form of they/them', syn: [] },
    who:       { pos: ['pronoun'], def: 'asking about or referring to a person', syn: ['whom', 'whoever'] },
    whom:      { pos: ['pronoun'], def: 'objective case of who', syn: ['who'] },
    whose:     { pos: ['pronoun', 'determiner'], def: 'possessive form of who', syn: [] },
    whoever:   { pos: ['pronoun'], def: 'any person who; no matter who', syn: ['anyone who', 'whomever'] },
    what:      { pos: ['pronoun', 'determiner'], def: 'asking for information', syn: [] },
    when:      { pos: ['adverb', 'conjunction'], def: 'at what time; at the time that', syn: ['while', 'whenever'] },
    whenever:  { pos: ['conjunction', 'adverb'], def: 'at whatever time; every time that', syn: ['anytime', 'each time'] },
    where:     { pos: ['adverb', 'conjunction'], def: 'in or to what place', syn: ['wherever'] },
    another:   { pos: ['pronoun', 'determiner'], def: 'one more; a different one', syn: ['additional', 'different', 'other'] },
    anybody:   { pos: ['pronoun'], def: 'any person', syn: ['anyone', 'somebody'] },
    anyone:    { pos: ['pronoun'], def: 'any person at all', syn: ['anybody', 'someone'] },
    anything:  { pos: ['pronoun'], def: 'any thing at all', syn: ['something', 'whatever'] },
    everyone:  { pos: ['pronoun'], def: 'every person', syn: ['everybody', 'all'] },
    everybody: { pos: ['pronoun'], def: 'every person', syn: ['everyone', 'all'] },
    everything:{ pos: ['pronoun'], def: 'all things; all that exists', syn: ['all', 'the lot'] },
    something: { pos: ['pronoun'], def: 'an unspecified thing', syn: ['anything', 'object'] },
    both:      { pos: ['pronoun', 'determiner'], def: 'the two; each of two', syn: ['each', 'the pair'] },
    every:     { pos: ['determiner'], def: 'each one of a group without exception', syn: ['each', 'all'] },
    several:   { pos: ['determiner', 'pronoun'], def: 'more than two but not very many', syn: ['some', 'a few', 'various'] },

    // ── Auxiliary/modal verbs & common verb forms ────────────────────
    is:        { pos: ['verb'], def: 'third person singular present of be', syn: ['exists', 'equals'] },
    was:       { pos: ['verb'], def: 'past tense of be (first/third person singular)', syn: [] },
    were:      { pos: ['verb'], def: 'past tense of be (plural/second person)', syn: [] },
    been:      { pos: ['verb'], def: 'past participle of be', syn: [] },
    has:       { pos: ['verb'], def: 'third person singular present of have', syn: ['possesses', 'owns'] },
    had:       { pos: ['verb'], def: 'past tense and past participle of have', syn: ['possessed', 'owned'] },
    does:      { pos: ['verb'], def: 'third person singular present of do', syn: ['performs', 'executes'] },
    did:       { pos: ['verb'], def: 'past tense of do', syn: ['performed', 'completed'] },
    could:     { pos: ['verb'], def: 'past tense of can; expressing possibility', syn: ['might', 'was able to'] },
    would:     { pos: ['verb'], def: 'past tense of will; expressing conditional', syn: ['might'] },
    should:    { pos: ['verb'], def: 'expressing obligation or expectation', syn: ['ought to', 'must'] },
    shall:     { pos: ['verb'], def: 'expressing future tense or determination', syn: ['will'] },
    goes:      { pos: ['verb'], def: 'third person singular present of go', syn: ['travels', 'moves'] },
    went:      { pos: ['verb'], def: 'past tense of go', syn: ['traveled', 'departed'] },
    came:      { pos: ['verb'], def: 'past tense of come', syn: ['arrived', 'approached'] },
    got:       { pos: ['verb'], def: 'past tense of get', syn: ['obtained', 'received', 'acquired'] },
    gave:      { pos: ['verb'], def: 'past tense of give', syn: ['donated', 'presented', 'offered'] },
    said:      { pos: ['verb'], def: 'past tense of say', syn: ['stated', 'declared', 'uttered'] },
    told:      { pos: ['verb'], def: 'past tense of tell', syn: ['informed', 'notified', 'narrated'] },
    took:      { pos: ['verb'], def: 'past tense of take', syn: ['grabbed', 'seized', 'accepted'] },
    knew:      { pos: ['verb'], def: 'past tense of know', syn: ['understood', 'recognized'] },
    met:       { pos: ['verb'], def: 'past tense of meet', syn: ['encountered', 'greeted'] },
    ran:       { pos: ['verb'], def: 'past tense of run', syn: ['sprinted', 'dashed', 'jogged'] },
    rang:      { pos: ['verb'], def: 'past tense of ring', syn: ['chimed', 'sounded', 'tolled'] },
    wrote:     { pos: ['verb'], def: 'past tense of write', syn: ['penned', 'authored', 'composed'] },
    wore:      { pos: ['verb'], def: 'past tense of wear', syn: ['donned', 'sported'] },
    rode:      { pos: ['verb'], def: 'past tense of ride', syn: ['traveled', 'drove'] },
    flew:      { pos: ['verb'], def: 'past tense of fly', syn: ['soared', 'glided'] },
    grew:      { pos: ['verb'], def: 'past tense of grow', syn: ['expanded', 'increased', 'developed'] },
    threw:     { pos: ['verb'], def: 'past tense of throw', syn: ['hurled', 'tossed', 'flung'] },
    drank:     { pos: ['verb'], def: 'past tense of drink', syn: ['sipped', 'consumed', 'gulped'] },
    swore:     { pos: ['verb'], def: 'past tense of swear', syn: ['vowed', 'pledged', 'cursed'] },
    froze:     { pos: ['verb'], def: 'past tense of freeze', syn: ['solidified', 'iced', 'chilled'] },
    forgave:   { pos: ['verb'], def: 'past tense of forgive', syn: ['pardoned', 'excused', 'absolved'] },
    trod:      { pos: ['verb'], def: 'past tense of tread', syn: ['walked', 'stepped', 'trampled'] },
    woke:      { pos: ['verb', 'adjective'], def: 'past tense of wake; alert to social injustice', syn: ['awakened', 'arose', 'aware'] },
    fled:      { pos: ['verb'], def: 'past tense of flee', syn: ['escaped', 'ran away', 'bolted'] },
    hid:       { pos: ['verb'], def: 'past tense of hide', syn: ['concealed', 'stashed', 'secreted'] },
    hung:      { pos: ['verb'], def: 'past tense of hang', syn: ['suspended', 'dangled', 'draped'] },
    caught:    { pos: ['verb'], def: 'past tense of catch', syn: ['captured', 'seized', 'grabbed'] },
    eaten:     { pos: ['verb'], def: 'past participle of eat', syn: ['consumed', 'devoured'] },
    seen:      { pos: ['verb'], def: 'past participle of see', syn: ['observed', 'witnessed', 'viewed'] },
    shown:     { pos: ['verb'], def: 'past participle of show', syn: ['displayed', 'exhibited', 'demonstrated'] },
    stolen:    { pos: ['verb', 'adjective'], def: 'past participle of steal; taken unlawfully', syn: ['taken', 'pilfered', 'swiped'] },
    stood:     { pos: ['verb'], def: 'past tense of stand', syn: ['remained', 'rose', 'endured'] },
    began:     { pos: ['verb'], def: 'past tense of begin', syn: ['started', 'commenced', 'initiated'] },
    women:     { pos: ['noun'], def: 'plural of woman', syn: ['ladies', 'females'] },
    feet:      { pos: ['noun'], def: 'plural of foot', syn: [] },

    // ── Contractions (apostrophe-stripped) ───────────────────────────
    ive:       { pos: ['contraction'], def: "contraction of 'I have'", syn: [] },
    youre:     { pos: ['contraction'], def: "contraction of 'you are'", syn: [] },
    youve:     { pos: ['contraction'], def: "contraction of 'you have'", syn: [] },
    youll:     { pos: ['contraction'], def: "contraction of 'you will'", syn: [] },
    youd:      { pos: ['contraction'], def: "contraction of 'you would' or 'you had'", syn: [] },
    hes:       { pos: ['contraction'], def: "contraction of 'he is' or 'he has'", syn: [] },
    hed:       { pos: ['contraction'], def: "contraction of 'he would' or 'he had'", syn: [] },
    shes:      { pos: ['contraction'], def: "contraction of 'she is' or 'she has'", syn: [] },
    itll:      { pos: ['contraction'], def: "contraction of 'it will'", syn: [] },
    weve:      { pos: ['contraction'], def: "contraction of 'we have'", syn: [] },
    theyre:    { pos: ['contraction'], def: "contraction of 'they are'", syn: [] },
    theyve:    { pos: ['contraction'], def: "contraction of 'they have'", syn: [] },
    theyll:    { pos: ['contraction'], def: "contraction of 'they will'", syn: [] },
    theyd:     { pos: ['contraction'], def: "contraction of 'they would' or 'they had'", syn: [] },
    thatll:    { pos: ['contraction'], def: "contraction of 'that will'", syn: [] },
    wholl:     { pos: ['contraction'], def: "contraction of 'who will'", syn: [] },
    whod:      { pos: ['contraction'], def: "contraction of 'who would' or 'who had'", syn: [] },
    whats:     { pos: ['contraction'], def: "contraction of 'what is' or 'what has'", syn: [] },
    whatll:    { pos: ['contraction'], def: "contraction of 'what will'", syn: [] },
    theres:    { pos: ['contraction'], def: "contraction of 'there is' or 'there has'", syn: [] },
    hows:      { pos: ['contraction'], def: "contraction of 'how is' or 'how has'", syn: [] },
    whens:     { pos: ['contraction'], def: "contraction of 'when is' or 'when has'", syn: [] },
    whys:      { pos: ['contraction'], def: "contraction of 'why is' or 'why has'", syn: [] },
    isnt:      { pos: ['contraction'], def: "contraction of 'is not'", syn: [] },
    arent:     { pos: ['contraction'], def: "contraction of 'are not'", syn: [] },
    wasnt:     { pos: ['contraction'], def: "contraction of 'was not'", syn: [] },
    werent:    { pos: ['contraction'], def: "contraction of 'were not'", syn: [] },
    dont:      { pos: ['contraction'], def: "contraction of 'do not'", syn: [] },
    doesnt:    { pos: ['contraction'], def: "contraction of 'does not'", syn: [] },
    didnt:     { pos: ['contraction'], def: "contraction of 'did not'", syn: [] },
    wont:      { pos: ['contraction'], def: "contraction of 'will not'", syn: [] },
    wouldnt:   { pos: ['contraction'], def: "contraction of 'would not'", syn: [] },
    shouldnt:  { pos: ['contraction'], def: "contraction of 'should not'", syn: [] },
    couldnt:   { pos: ['contraction'], def: "contraction of 'could not'", syn: [] },
    cant:      { pos: ['contraction'], def: "contraction of 'cannot'", syn: [] },
    cannot:    { pos: ['verb'], def: 'be unable to; not be able to', syn: ["can't"] },
    havent:    { pos: ['contraction'], def: "contraction of 'have not'", syn: [] },
    hasnt:     { pos: ['contraction'], def: "contraction of 'has not'", syn: [] },
    hadnt:     { pos: ['contraction'], def: "contraction of 'had not'", syn: [] },
    mustnt:    { pos: ['contraction'], def: "contraction of 'must not'", syn: [] },
    neednt:    { pos: ['contraction'], def: "contraction of 'need not'", syn: [] },
    aint:      { pos: ['contraction'], def: "informal contraction of 'am not', 'is not', 'are not', 'has not', or 'have not'", syn: [] },
    couldve:   { pos: ['contraction'], def: "contraction of 'could have'", syn: [] },
    shouldve:  { pos: ['contraction'], def: "contraction of 'should have'", syn: [] },
    wouldve:   { pos: ['contraction'], def: "contraction of 'would have'", syn: [] },
    mightve:   { pos: ['contraction'], def: "contraction of 'might have'", syn: [] },
    mustve:    { pos: ['contraction'], def: "contraction of 'must have'", syn: [] },
    whove:     { pos: ['contraction'], def: "contraction of 'who have'", syn: [] },
    thered:    { pos: ['contraction'], def: "contraction of 'there would' or 'there had'", syn: [] },
    whered:    { pos: ['contraction'], def: "contraction of 'where did'", syn: [] },
    whatd:     { pos: ['contraction'], def: "contraction of 'what did' or 'what would'", syn: [] },
    howd:      { pos: ['contraction'], def: "contraction of 'how did'", syn: [] },
    therell:   { pos: ['contraction'], def: "contraction of 'there will'", syn: [] },
    itve:      { pos: ['contraction'], def: "contraction of 'it have' (informal)", syn: [] },

    // ── Informal / slang ────────────────────────────────────────────
    wanna:     { pos: ['contraction'], def: "informal for 'want to'", syn: [] },
    gotta:     { pos: ['contraction'], def: "informal for 'got to' or 'have to'", syn: [] },
    yall:      { pos: ['contraction'], def: "informal for 'you all' (Southern US)", syn: [] },
    maam:      { pos: ['noun'], def: "polite form of address for a woman (contraction of madam)", syn: ['madam', 'ma\'am'] },
    oclock:    { pos: ['adverb'], def: "used to specify the hour (contraction of 'of the clock')", syn: [] },
    gonna:     { pos: ['contraction'], def: "informal for 'going to'", syn: [] },
    ya:        { pos: ['pronoun'], def: 'informal for you', syn: ['you'] },
    ye:        { pos: ['pronoun'], def: 'archaic/dialectal form of you', syn: ['you'] },
    yep:       { pos: ['interjection'], def: 'informal for yes', syn: ['yes', 'yeah', 'yup'] },
    hey:       { pos: ['interjection'], def: 'used to attract attention or express surprise', syn: ['hi', 'hello', 'yo'] },
    ah:        { pos: ['interjection'], def: 'expressing realization, relief, or sympathy', syn: ['oh', 'aha'] },
    aw:        { pos: ['interjection'], def: 'expressing sympathy or disappointment', syn: ['oh', 'alas'] },
    ay:        { pos: ['interjection'], def: 'expressing agreement or acknowledgment', syn: ['aye', 'yes'] },
    uh:        { pos: ['interjection'], def: 'expressing hesitation', syn: ['um', 'er'] },
    um:        { pos: ['interjection'], def: 'expressing hesitation or pause', syn: ['uh', 'er'] },
    ow:        { pos: ['interjection'], def: 'expressing sudden pain', syn: ['ouch'] },
    bo:        { pos: ['interjection', 'noun'], def: 'exclamation to startle; informal for buddy', syn: ['bro', 'pal'] },
    lo:        { pos: ['interjection'], def: 'archaic exclamation to draw attention (lo and behold)', syn: ['behold'] },
    wo:        { pos: ['interjection'], def: 'variant of whoa; command to stop', syn: ['whoa'] },
    im:        { pos: ['contraction'], def: "contraction of 'I am'", syn: [] },
    op:        { pos: ['noun'], def: 'operation; original poster (internet slang)', syn: ['operation'] },

    // ── Modern tech / digital terms ─────────────────────────────────
    app:       { pos: ['noun'], def: 'a software application, especially for mobile devices', syn: ['application', 'program', 'software'] },
    emoji:     { pos: ['noun'], def: 'a small digital image or icon used to express an idea or emotion', syn: ['emoticon', 'smiley', 'icon'] },
    bitcoin:   { pos: ['noun'], def: 'a decentralized digital cryptocurrency', syn: ['crypto', 'cryptocurrency', 'btc'] },
    blockchain:{ pos: ['noun'], def: 'a distributed digital ledger recording transactions', syn: ['distributed ledger', 'chain'] },
    bluetooth: { pos: ['noun'], def: 'a wireless technology standard for short-range data exchange', syn: ['wireless'] },
    crypto:    { pos: ['noun'], def: 'short for cryptocurrency; digital currency using cryptography', syn: ['cryptocurrency', 'bitcoin', 'digital currency'] },
    vpn:       { pos: ['noun'], def: 'virtual private network; encrypted internet connection', syn: ['virtual private network'] },
    gpu:       { pos: ['noun'], def: 'graphics processing unit; hardware for rendering images', syn: ['graphics card', 'video card'] },
    admin:     { pos: ['noun'], def: 'short for administrator; person managing a system', syn: ['administrator', 'manager', 'sysadmin'] },
    antivirus: { pos: ['noun', 'adjective'], def: 'software designed to detect and remove computer viruses', syn: ['malware protection', 'security software'] },
    barcode:   { pos: ['noun'], def: 'a machine-readable code of parallel lines representing data', syn: ['upc', 'qr code'] },
    captcha:   { pos: ['noun'], def: 'a test to distinguish humans from bots on websites', syn: ['verification', 'bot check'] },
    chatbot:   { pos: ['noun'], def: 'a computer program that simulates human conversation', syn: ['bot', 'virtual assistant', 'ai assistant'] },
    clickbait: { pos: ['noun'], def: 'sensationalized online content designed to attract clicks', syn: ['bait', 'sensationalism'] },
    codec:     { pos: ['noun'], def: 'software that compresses and decompresses digital media', syn: ['encoder', 'decoder', 'compressor'] },
    deepfake:  { pos: ['noun'], def: 'AI-generated fake video or audio that appears real', syn: ['synthetic media', 'ai fake'] },
    defrag:    { pos: ['verb', 'noun'], def: 'reorganize data on a disk to improve access speed', syn: ['defragment', 'optimize'] },
    fintech:   { pos: ['noun'], def: 'financial technology; tech-driven financial services', syn: ['financial technology'] },
    frontend:  { pos: ['noun', 'adjective'], def: 'the user-facing part of a website or application', syn: ['client-side', 'ui', 'interface'] },
    fullstack: { pos: ['adjective'], def: 'able to work on both frontend and backend development', syn: ['full-stack'] },
    hashtag:   { pos: ['noun'], def: 'a word or phrase preceded by # used on social media', syn: ['tag', 'label'] },
    hotfix:    { pos: ['noun'], def: 'an urgent software patch applied to fix a critical bug', syn: ['patch', 'bugfix', 'fix'] },
    inbox:     { pos: ['noun'], def: 'a receptacle for incoming messages, especially email', syn: ['mailbox', 'messages'] },
    inkjet:    { pos: ['noun', 'adjective'], def: 'a type of printer that sprays tiny ink droplets', syn: ['printer'] },
    login:     { pos: ['noun', 'verb'], def: 'the process of signing into a computer system', syn: ['sign in', 'log on', 'authenticate'] },
    megapixel: { pos: ['noun'], def: 'one million pixels; a measure of camera resolution', syn: ['mp'] },
    middleware:{ pos: ['noun'], def: 'software that connects different applications or systems', syn: ['connector', 'bridge'] },
    motherboard:{ pos: ['noun'], def: 'the main circuit board in a computer', syn: ['mainboard', 'logic board'] },
    offline:   { pos: ['adjective', 'adverb'], def: 'not connected to the internet or a network', syn: ['disconnected', 'unplugged'] },
    phishing:  { pos: ['noun'], def: 'fraudulent attempt to obtain sensitive data by impersonating a trusted entity', syn: ['scam', 'fraud', 'spoofing'] },
    plugin:    { pos: ['noun'], def: 'a software component that adds features to an existing program', syn: ['extension', 'add-on', 'module'] },
    popup:     { pos: ['noun', 'adjective'], def: 'a window or element that appears suddenly on screen', syn: ['pop-up', 'dialog', 'overlay'] },
    ransomware:{ pos: ['noun'], def: 'malware that encrypts data and demands payment for its release', syn: ['malware', 'extortion software'] },
    screenshot:{ pos: ['noun'], def: 'an image capture of a computer screen display', syn: ['screen capture', 'screengrab'] },
    selfie:    { pos: ['noun'], def: 'a self-portrait photograph taken with a smartphone', syn: ['self-portrait', 'self-photo'] },
    smartphone:{ pos: ['noun'], def: 'a mobile phone with advanced computing capabilities', syn: ['phone', 'mobile', 'cell phone'] },
    subnet:    { pos: ['noun'], def: 'a logical subdivision of a computer network', syn: ['subnetwork'] },
    taskbar:   { pos: ['noun'], def: 'a bar on a computer screen showing running programs', syn: ['toolbar', 'dock'] },
    toolbar:   { pos: ['noun'], def: 'a strip of icons providing quick access to software functions', syn: ['taskbar', 'ribbon', 'menu bar'] },
    username:  { pos: ['noun'], def: 'a unique identifier used to log into a system', syn: ['user id', 'handle', 'login name'] },
    webinar:   { pos: ['noun'], def: 'a seminar or presentation conducted over the internet', syn: ['web seminar', 'online workshop'] },
    whiteboard:{ pos: ['noun'], def: 'a smooth white surface for writing with markers', syn: ['dry-erase board'] },
    whitelist: { pos: ['noun', 'verb'], def: 'a list of approved items; to approve or allow', syn: ['allowlist', 'approved list'] },
    uninstall: { pos: ['verb'], def: 'to remove software from a computer', syn: ['remove', 'delete', 'unload'] },
    analytics: { pos: ['noun'], def: 'systematic analysis of data or statistics', syn: ['data analysis', 'metrics', 'statistics'] },
    demographics:{ pos: ['noun'], def: 'statistical data about the characteristics of a population', syn: ['population statistics', 'census data'] },
    runtime:   { pos: ['noun'], def: 'the period during which a program is executing', syn: ['execution time'] },
    timeout:   { pos: ['noun'], def: 'a period of inactivity after which a process is halted', syn: ['time limit', 'expiration'] },

    // ── Compound / blended words ────────────────────────────────────
    airbag:    { pos: ['noun'], def: 'an inflatable safety device in vehicles', syn: ['safety cushion'] },
    breakdance:{ pos: ['noun', 'verb'], def: 'an acrobatic style of street dancing', syn: ['bboy', 'breaking'] },
    burnout:   { pos: ['noun'], def: 'physical or mental exhaustion from overwork', syn: ['exhaustion', 'fatigue', 'collapse'] },
    carpool:   { pos: ['noun', 'verb'], def: 'sharing a car journey with others to reduce costs', syn: ['rideshare', 'carshare'] },
    cashback:  { pos: ['noun'], def: 'a rebate of money after a purchase', syn: ['rebate', 'refund'] },
    cliffside: { pos: ['noun', 'adjective'], def: 'the side or face of a cliff', syn: ['cliff face', 'escarpment'] },
    coffeetable:{ pos: ['noun'], def: 'a low table placed in front of a sofa', syn: ['cocktail table'] },
    coworker:  { pos: ['noun'], def: 'a person one works with', syn: ['colleague', 'workmate', 'associate'] },
    dragonfruit:{ pos: ['noun'], def: 'a tropical fruit with bright pink skin and white flesh', syn: ['pitaya', 'pitahaya'] },
    endtable:  { pos: ['noun'], def: 'a small table placed beside a chair or at the end of a sofa', syn: ['side table', 'nightstand'] },
    firetruck: { pos: ['noun'], def: 'a vehicle equipped for firefighting', syn: ['fire engine', 'fire apparatus'] },
    frontline: { pos: ['noun', 'adjective'], def: 'the foremost position in a conflict or activity', syn: ['front line', 'vanguard', 'forefront'] },
    homerun:   { pos: ['noun'], def: 'a hit in baseball allowing the batter to circle all bases', syn: ['homer', 'home run'] },
    hoodie:    { pos: ['noun'], def: 'a sweatshirt with a hood', syn: ['hooded sweatshirt', 'pullover'] },
    jawline:   { pos: ['noun'], def: 'the contour of the lower jaw', syn: ['jaw', 'mandible line'] },
    keychain:  { pos: ['noun'], def: 'a ring or chain for holding keys', syn: ['key ring', 'key fob'] },
    kickball:  { pos: ['noun'], def: 'a playground game similar to baseball using a rubber ball', syn: [] },
    kickstart: { pos: ['verb', 'noun'], def: 'to start or restart a process with energy', syn: ['jumpstart', 'ignite', 'launch'] },
    leggings:  { pos: ['noun'], def: 'tight-fitting stretch pants', syn: ['tights', 'yoga pants'] },
    livecast:  { pos: ['noun', 'verb'], def: 'a live broadcast over the internet', syn: ['livestream', 'live broadcast'] },
    livestream:{ pos: ['noun', 'verb'], def: 'live audio/video transmitted over the internet', syn: ['stream', 'live broadcast', 'livecast'] },
    multitask: { pos: ['verb'], def: 'to perform multiple tasks simultaneously', syn: ['juggle'] },
    nightstand:{ pos: ['noun'], def: 'a small table beside a bed', syn: ['bedside table', 'nighttable'] },
    pajamas:   { pos: ['noun'], def: 'loose-fitting clothing worn for sleeping', syn: ['pyjamas', 'sleepwear', 'nightwear'] },
    panties:   { pos: ['noun'], def: "women's or children's underwear", syn: ['underwear', 'underpants', 'knickers'] },
    passionfruit:{ pos: ['noun'], def: 'a tropical fruit with a tart, seedy interior', syn: ['passion fruit', 'maracuja'] },
    placemat:  { pos: ['noun'], def: 'a mat placed under a plate on a table', syn: ['table mat'] },
    prequel:   { pos: ['noun'], def: 'a story set before the events of an existing work', syn: ['predecessor', 'backstory'] },
    rebrand:   { pos: ['verb'], def: 'to change the image or identity of a product or company', syn: ['rename', 'relaunch', 'reimagine'] },
    reconfigure:{ pos: ['verb'], def: 'to configure something differently', syn: ['rearrange', 'reorganize', 'adjust'] },
    reimagine: { pos: ['verb'], def: 'to imagine again or differently; to reinvent', syn: ['rethink', 'reinvent', 'reinterpret'] },
    reinvest:  { pos: ['verb'], def: 'to invest money again, especially profits', syn: ['plow back', 'recycle funds'] },
    remix:     { pos: ['noun', 'verb'], def: 'an altered version of a song; to alter and recombine', syn: ['rework', 'mashup', 'arrangement'] },
    retweet:   { pos: ['noun', 'verb'], def: 'to share another user\'s post on social media', syn: ['share', 'repost'] },
    ribcage:   { pos: ['noun'], def: 'the bony framework of the chest formed by the ribs', syn: ['rib cage', 'thorax'] },
    ringtone:  { pos: ['noun'], def: 'a sound made by a phone to signal an incoming call', syn: ['tone', 'alert sound'] },
    storyboard:{ pos: ['noun', 'verb'], def: 'a sequence of drawings representing shots for a film', syn: ['shot list', 'visual plan'] },
    telecommute:{ pos: ['verb'], def: 'to work from home using telecommunications', syn: ['remote work', 'work from home'] },
    tracksuit: { pos: ['noun'], def: 'a matching jacket and pants worn for exercise', syn: ['sweatsuit', 'warmup suit'] },
    trailside: { pos: ['adjective', 'noun'], def: 'located at the side of a trail', syn: ['trail-adjacent'] },
    triathlon: { pos: ['noun'], def: 'an athletic contest of three events (swimming, cycling, running)', syn: ['triple event'] },
    tollway:   { pos: ['noun'], def: 'a road where a fee is charged for use', syn: ['turnpike', 'toll road'] },
    warmup:    { pos: ['noun'], def: 'a period of gentle exercise before intense activity', syn: ['warm-up', 'stretching'] },
    starfruit: { pos: ['noun'], def: 'a tropical fruit with a star-shaped cross-section', syn: ['carambola'] },
    brushstroke:{ pos: ['noun'], def: 'a single stroke of a paintbrush', syn: ['stroke', 'mark'] },
    standup:   { pos: ['noun', 'adjective'], def: 'a comedy performance; an upright position', syn: ['comedy', 'stand-up'] },
    overcooked:{ pos: ['adjective'], def: 'cooked for too long', syn: ['overdone', 'burnt'] },
    payout:    { pos: ['noun'], def: 'a large payment of money', syn: ['payment', 'disbursement', 'settlement'] },
    phaseout:  { pos: ['noun'], def: 'a gradual discontinuation or withdrawal', syn: ['discontinuation', 'elimination'] },

    // ── Past participles / verb forms used as adjectives ─────────────
    adding:    { pos: ['verb'], def: 'present participle of add', syn: ['including', 'appending'] },
    conflicted:{ pos: ['adjective'], def: 'having mixed feelings or contradictory ideas', syn: ['torn', 'ambivalent', 'divided'] },
    defended:  { pos: ['verb', 'adjective'], def: 'past tense of defend; protected', syn: ['protected', 'guarded', 'shielded'] },
    devastated:{ pos: ['adjective'], def: 'extremely shocked and upset', syn: ['shattered', 'crushed', 'heartbroken'] },
    donated:   { pos: ['verb'], def: 'past tense of donate; gave to a cause', syn: ['contributed', 'gifted', 'gave'] },
    dropped:   { pos: ['verb'], def: 'past tense of drop; let fall', syn: ['fell', 'released', 'lowered'] },
    drops:     { pos: ['noun', 'verb'], def: 'small amounts of liquid; third person of drop', syn: ['drips', 'beads', 'falls'] },
    drying:    { pos: ['verb', 'adjective'], def: 'present participle of dry; becoming dry', syn: ['dehydrating', 'evaporating'] },
    easier:    { pos: ['adjective'], def: 'comparative form of easy', syn: ['simpler', 'less difficult'] },
    failed:    { pos: ['adjective', 'verb'], def: 'unsuccessful; past tense of fail', syn: ['unsuccessful', 'botched'] },
    forsaken:  { pos: ['adjective'], def: 'abandoned or deserted', syn: ['abandoned', 'deserted', 'neglected'] },
    frazzled:  { pos: ['adjective'], def: 'completely exhausted or worn out', syn: ['exhausted', 'stressed', 'drained'] },
    harrowed:  { pos: ['adjective', 'verb'], def: 'deeply distressed; cultivated with a harrow', syn: ['distressed', 'tormented'] },
    hoping:    { pos: ['verb'], def: 'present participle of hope', syn: ['wishing', 'expecting'] },
    hosting:   { pos: ['verb', 'noun'], def: 'present participle of host; providing server space', syn: ['serving', 'running'] },
    impressed: { pos: ['adjective'], def: 'feeling admiration or respect', syn: ['amazed', 'awed', 'admiring'] },
    implied:   { pos: ['adjective', 'verb'], def: 'suggested but not directly expressed', syn: ['suggested', 'hinted', 'inferred'] },
    insulted:  { pos: ['adjective', 'verb'], def: 'feeling offended or disrespected', syn: ['offended', 'affronted'] },
    irked:     { pos: ['adjective', 'verb'], def: 'irritated or annoyed', syn: ['annoyed', 'irritated', 'vexed'] },
    ashamed:   { pos: ['adjective'], def: 'feeling shame or embarrassment', syn: ['embarrassed', 'humiliated', 'mortified'] },
    aghast:    { pos: ['adjective'], def: 'filled with horror or shock', syn: ['horrified', 'appalled', 'stunned'] },
    immersive: { pos: ['adjective'], def: 'providing a deeply engaging experience', syn: ['absorbing', 'engrossing', 'captivating'] },
    lone:      { pos: ['adjective'], def: 'solitary; single and isolated', syn: ['sole', 'solitary', 'single'] },
    nerdy:     { pos: ['adjective'], def: 'unfashionably studious; obsessively interested in tech', syn: ['geeky', 'bookish'] },
    opted:     { pos: ['verb'], def: 'past tense of opt; made a choice', syn: ['chose', 'selected', 'decided'] },
    pampered:  { pos: ['adjective'], def: 'treated with excessive indulgence', syn: ['spoiled', 'indulged', 'coddled'] },
    petrified: { pos: ['adjective'], def: 'extremely frightened; turned to stone', syn: ['terrified', 'paralyzed', 'frozen'] },
    previous:  { pos: ['adjective'], def: 'occurring before in time or order', syn: ['prior', 'preceding', 'former'] },
    repulsed:  { pos: ['adjective'], def: 'feeling intense distaste or disgust', syn: ['disgusted', 'revolted', 'repelled'] },
    respective:{ pos: ['adjective'], def: 'belonging separately to each of those in question', syn: ['individual', 'separate', 'particular'] },
    resulting: { pos: ['adjective'], def: 'occurring as a consequence', syn: ['consequent', 'ensuing', 'following'] },
    revolted:  { pos: ['adjective'], def: 'feeling intense disgust', syn: ['disgusted', 'repulsed', 'sickened'] },
    sickened:  { pos: ['adjective', 'verb'], def: 'feeling nauseous or disgusted', syn: ['nauseated', 'disgusted', 'repulsed'] },
    softer:    { pos: ['adjective'], def: 'comparative form of soft', syn: ['gentler', 'smoother'] },
    staffed:   { pos: ['adjective', 'verb'], def: 'provided with staff or employees', syn: ['manned', 'crewed'] },
    strikes:   { pos: ['noun', 'verb'], def: 'industrial actions; hits forcefully', syn: ['hits', 'blows', 'attacks'] },
    studs:     { pos: ['noun'], def: 'plural of stud; metal pins or decorative buttons; wall supports', syn: ['pins', 'bolts', 'supports'] },
    updated:   { pos: ['adjective', 'verb'], def: 'made more current; past tense of update', syn: ['revised', 'modernized', 'refreshed'] },
    undervalued:{ pos: ['adjective'], def: 'not given enough worth or recognition', syn: ['underrated', 'underappreciated'] },
    unfazed:   { pos: ['adjective'], def: 'not disturbed or disconcerted', syn: ['unperturbed', 'composed', 'calm'] },
    workers:   { pos: ['noun'], def: 'plural of worker; people who work', syn: ['employees', 'laborers', 'staff'] },
    dogs:      { pos: ['noun'], def: 'plural of dog', syn: ['canines', 'hounds', 'pups'] },
    covers:    { pos: ['noun', 'verb'], def: 'plural of cover; things that cover; third person of cover', syn: ['shields', 'wraps', 'tops'] },
    fevers:    { pos: ['noun'], def: 'plural of fever; abnormally high body temperatures', syn: ['temperatures'] },
    kegs:      { pos: ['noun'], def: 'plural of keg; small barrels', syn: ['barrels', 'casks'] },
    keys:      { pos: ['noun'], def: 'plural of key; devices for opening locks', syn: ['locks'] },
    oats:      { pos: ['noun'], def: 'a cereal grain used as food', syn: ['oatmeal', 'grain', 'porridge'] },
    gums:      { pos: ['noun'], def: 'the firm tissue surrounding the teeth', syn: ['gingiva'] },

    // ── Food / drink ────────────────────────────────────────────────
    chai:      { pos: ['noun'], def: 'a spiced tea originating from India', syn: ['tea', 'masala chai'] },
    fajita:    { pos: ['noun'], def: 'a Tex-Mex dish of grilled meat served in a tortilla', syn: ['wrap', 'taco'] },
    jicama:    { pos: ['noun'], def: 'a crisp, sweet root vegetable native to Mexico', syn: ['yam bean', 'Mexican turnip'] },
    kombucha:  { pos: ['noun'], def: 'a fermented, sweetened tea drink', syn: ['fermented tea'] },
    matcha:    { pos: ['noun'], def: 'finely ground green tea powder', syn: ['green tea powder'] },
    sriracha:  { pos: ['noun'], def: 'a hot chili sauce originating from Thailand', syn: ['hot sauce', 'chili sauce'] },
    zester:    { pos: ['noun'], def: 'a kitchen tool for grating citrus peel', syn: ['grater', 'zesting tool'] },

    // ── Misc nouns / other ──────────────────────────────────────────
    joey:      { pos: ['noun'], def: 'a young kangaroo; a baby marsupial', syn: ['baby kangaroo'] },
    jake:      { pos: ['adjective', 'noun'], def: 'satisfactory; fine (slang); a man\'s name', syn: ['fine', 'okay'] },
    koi:       { pos: ['noun'], def: 'a colorful ornamental variety of carp', syn: ['ornamental carp'] },
    kayaking:  { pos: ['noun', 'verb'], def: 'the sport of traveling in a kayak', syn: ['paddling', 'canoeing'] },
    tutoring:  { pos: ['noun', 'verb'], def: 'the act of teaching or giving instruction', syn: ['teaching', 'coaching', 'mentoring'] },
    soulmate:  { pos: ['noun'], def: 'a person ideally suited to another', syn: ['kindred spirit', 'twin flame', 'partner'] },
    foci:      { pos: ['noun'], def: 'plural of focus; central points', syn: ['centers', 'focal points'] },
    media:     { pos: ['noun'], def: 'plural of medium; communication channels collectively', syn: ['press', 'news', 'broadcasting'] },
    virtual:   { pos: ['adjective'], def: 'existing in essence but not in physical form; computer-simulated', syn: ['digital', 'simulated', 'online'] },
    trans:     { pos: ['adjective', 'prefix'], def: 'across; on the other side of; transgender', syn: ['cross', 'across'] },
    mega:      { pos: ['adjective', 'prefix'], def: 'very large; a factor of one million', syn: ['huge', 'enormous', 'giant'] },
    hyper:     { pos: ['adjective', 'prefix'], def: 'excessively energetic; above or beyond', syn: ['overactive', 'energetic', 'frenzied'] },
    regards:   { pos: ['noun'], def: 'best wishes; expressions of goodwill', syn: ['respects', 'greetings', 'wishes'] },
    anytime:   { pos: ['adverb'], def: 'at any time; whenever', syn: ['whenever', 'always'] },
    else:      { pos: ['adverb', 'adjective'], def: 'in addition; different; otherwise', syn: ['otherwise', 'alternatively'] },
    facto:     { pos: ['adjective'], def: 'in fact; in reality (as in de facto)', syn: ['actual', 'real'] },
    folic:     { pos: ['adjective'], def: 'relating to folic acid (a B vitamin)', syn: ['folate'] },
    origins:   { pos: ['noun'], def: 'plural of origin; beginning points or sources', syn: ['sources', 'roots', 'beginnings'] },
    ought:     { pos: ['verb'], def: 'used to indicate duty, correctness, or expectation', syn: ['should', 'must'] },

    // ── Typo / concatenation in source ──────────────────────────────
    mysterynatural: { pos: ['adjective'], def: 'likely a typo for "mystery" + "natural"; mysterious and natural', syn: ['mysterious', 'natural'] },
    sidewaysn: { pos: ['adjective'], def: 'likely a typo for "sideways"; directed to one side', syn: ['sideways', 'lateral'] },
    illust:    { pos: ['noun'], def: 'abbreviation for illustration', syn: ['illustration', 'drawing'] },
    pam:       { pos: ['noun'], def: 'a name; cooking spray brand', syn: [] },

    // ── Words that slipped through ──────────────────────────────────
    clingy:    { pos: ['adjective'], def: 'tending to cling; overly attached or dependent', syn: ['needy', 'dependent', 'attached'] },
    eke:       { pos: ['verb'], def: 'to make something last by using sparingly (eke out)', syn: ['stretch', 'supplement'] },
    equals:    { pos: ['noun', 'verb'], def: 'plural of equal; people of same status; third person of equal', syn: ['peers', 'matches'] },
    how:       { pos: ['adverb'], def: 'in what way or manner; to what extent', syn: [] },
    permitted: { pos: ['adjective', 'verb'], def: 'allowed; past tense of permit', syn: ['allowed', 'authorized', 'approved'] },
    strategize:{ pos: ['verb'], def: 'to devise a strategy or plan', syn: ['plan', 'scheme', 'plot'] },
    subtext:   { pos: ['noun'], def: 'an underlying or implicit meaning', syn: ['undertone', 'implication', 'nuance'] },
};

// ── Build enriched format ───────────────────────────────────────────
function buildEntry(word) {
    const manual = manualEntries[word];
    if (manual) {
        return {
            word,
            definitions: [{ pos: manual.pos.join(', '), definition: manual.def }],
            synonyms: manual.syn.filter(s => /^[a-z]+$/.test(s)), // only single alpha words for game use
            partsOfSpeech: manual.pos,
        };
    }
    // Fallback: minimal entry
    return {
        word,
        definitions: [],
        synonyms: [],
        partsOfSpeech: [],
    };
}

// ── Process all missing words ───────────────────────────────────────
const result = {};
let covered = 0;
let uncovered = 0;

for (const word of missing) {
    const entry = buildEntry(word);
    result[word] = entry;
    if (entry.definitions.length > 0) covered++;
    else uncovered++;
}

console.log(`\nResults:`);
console.log(`  Manually defined: ${covered}`);
console.log(`  Still empty:      ${uncovered}`);
if (uncovered > 0) {
    const empty = missing.filter(w => result[w].definitions.length === 0);
    console.log(`  Empty words: ${empty.join(', ')}`);
}

// ── Merge into words-enriched.json ──────────────────────────────────
const enrichedPath = path.join(__dirname, 'words-enriched.json');
let existing = {};
if (fs.existsSync(enrichedPath)) {
    existing = JSON.parse(fs.readFileSync(enrichedPath, 'utf8'));
    console.log(`\nLoaded existing words-enriched.json with ${Object.keys(existing).length} entries`);
}

let added = 0;
for (const [word, entry] of Object.entries(result)) {
    if (!existing[word]) {
        existing[word] = entry;
        added++;
    }
}

fs.writeFileSync(enrichedPath, JSON.stringify(existing, null, 2));
console.log(`Added ${added} new entries to words-enriched.json`);
console.log(`Total entries: ${Object.keys(existing).length}`);
